/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thilangi
 */
public class menu extends javax.swing.JFrame {

    /**
     * this is the variable for get username details from the previous user interface after login
     */
    public String Username;

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addmenubtn = new javax.swing.JButton();
        randommenubtn = new javax.swing.JButton();
        submenubtn = new javax.swing.JButton();
        mulmenubtn = new javax.swing.JButton();
        divmenubtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        stuloginclosebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addmenubtn.setBackground(new java.awt.Color(153, 0, 0));
        addmenubtn.setFont(new java.awt.Font("Curlz MT", 1, 36)); // NOI18N
        addmenubtn.setForeground(new java.awt.Color(255, 255, 255));
        addmenubtn.setText("Addition");
        addmenubtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addmenubtn.setBorderPainted(false);
        addmenubtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addmenubtnMouseClicked(evt);
            }
        });
        jPanel2.add(addmenubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 150, -1));

        randommenubtn.setBackground(new java.awt.Color(153, 0, 0));
        randommenubtn.setFont(new java.awt.Font("Curlz MT", 1, 36)); // NOI18N
        randommenubtn.setForeground(new java.awt.Color(255, 255, 255));
        randommenubtn.setText("Random");
        randommenubtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        randommenubtn.setBorderPainted(false);
        randommenubtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                randommenubtnMouseClicked(evt);
            }
        });
        randommenubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randommenubtnActionPerformed(evt);
            }
        });
        jPanel2.add(randommenubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 140, -1));

        submenubtn.setBackground(new java.awt.Color(153, 0, 0));
        submenubtn.setFont(new java.awt.Font("Curlz MT", 1, 36)); // NOI18N
        submenubtn.setForeground(new java.awt.Color(255, 255, 255));
        submenubtn.setText("Subtraction");
        submenubtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submenubtn.setBorderPainted(false);
        submenubtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submenubtnMouseClicked(evt);
            }
        });
        jPanel2.add(submenubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 190, -1));

        mulmenubtn.setBackground(new java.awt.Color(153, 0, 0));
        mulmenubtn.setFont(new java.awt.Font("Curlz MT", 1, 36)); // NOI18N
        mulmenubtn.setForeground(new java.awt.Color(255, 255, 255));
        mulmenubtn.setText("Multiplication");
        mulmenubtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mulmenubtn.setBorderPainted(false);
        mulmenubtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mulmenubtnMouseClicked(evt);
            }
        });
        jPanel2.add(mulmenubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 240, -1));

        divmenubtn.setBackground(new java.awt.Color(153, 0, 0));
        divmenubtn.setFont(new java.awt.Font("Curlz MT", 1, 36)); // NOI18N
        divmenubtn.setForeground(new java.awt.Color(255, 255, 255));
        divmenubtn.setText("Division");
        divmenubtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        divmenubtn.setBorderPainted(false);
        divmenubtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divmenubtnMouseClicked(evt);
            }
        });
        jPanel2.add(divmenubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 140, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Curlz MT", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Instructions");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 200, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image 2.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -190, 810, 660));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 26, 820, 450));

        stuloginclosebtn.setBackground(new java.awt.Color(255, 255, 255));
        stuloginclosebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_delete_40px.png"))); // NOI18N
        stuloginclosebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stuloginclosebtnMouseClicked(evt);
            }
        });
        jPanel1.add(stuloginclosebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void randommenubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randommenubtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_randommenubtnActionPerformed

    private void stuloginclosebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuloginclosebtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new images().setVisible(true);
    }//GEN-LAST:event_stuloginclosebtnMouseClicked

    private void addmenubtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addmenubtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new AdditionQuiz().setVisible(true);
    }//GEN-LAST:event_addmenubtnMouseClicked

    private void randommenubtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_randommenubtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new RandomQuiz().setVisible(true);
    }//GEN-LAST:event_randommenubtnMouseClicked

    private void submenubtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submenubtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new SubQuiz().setVisible(true);
    }//GEN-LAST:event_submenubtnMouseClicked

    private void mulmenubtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulmenubtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new MulQuiz().setVisible(true);
    }//GEN-LAST:event_mulmenubtnMouseClicked

    private void divmenubtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divmenubtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new DivQUiz().setVisible(true);
    }//GEN-LAST:event_divmenubtnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new instructions().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmenubtn;
    private javax.swing.JButton divmenubtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mulmenubtn;
    private javax.swing.JButton randommenubtn;
    private javax.swing.JButton stuloginclosebtn;
    private javax.swing.JButton submenubtn;
    // End of variables declaration//GEN-END:variables
}

// references
//https://youtu.be/jMgWl-0-JaY