
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.connectionProvider;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Thilangi
 */
public class userSignin extends javax.swing.JFrame {

    /**
     * Creates new form userSignin
     */
    public userSignin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stuloginclosebtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        passwordlogin = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernamelogin = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        usersigninbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Curlz MT", 1, 65)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("QUICK QUIZ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Test your knowledge on math with this simple quiz ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image 1.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        stuloginclosebtn.setBackground(new java.awt.Color(255, 255, 255));
        stuloginclosebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_delete_40px_1.png"))); // NOI18N
        stuloginclosebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stuloginclosebtnMouseClicked(evt);
            }
        });
        jPanel2.add(stuloginclosebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 500));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(450, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordlogin.setBackground(new java.awt.Color(204, 0, 0));
        passwordlogin.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        passwordlogin.setForeground(new java.awt.Color(204, 255, 204));
        passwordlogin.setText("Password");
        passwordlogin.setBorder(null);
        passwordlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordloginActionPerformed(evt);
            }
        });
        passwordlogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordloginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordloginFocusLost(evt);
            }
        });
        jPanel3.add(passwordlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 250, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 250, 20));

        jPanel5.setBackground(new java.awt.Color(0, 153, 0));
        jPanel5.setForeground(new java.awt.Color(204, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("    Sign In");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 2, true));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("   Sign Up");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 2, true));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 30));

        usernamelogin.setBackground(new java.awt.Color(204, 0, 0));
        usernamelogin.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        usernamelogin.setForeground(new java.awt.Color(204, 255, 204));
        usernamelogin.setText("User Name");
        usernamelogin.setBorder(null);
        usernamelogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameloginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameloginFocusLost(evt);
            }
        });
        jPanel3.add(usernamelogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 250, -1));

        jSeparator3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, 20));

        jPanel7.setBackground(new java.awt.Color(0, 153, 0));
        jPanel7.setForeground(new java.awt.Color(204, 0, 0));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setText("    Sign Up");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 2, true));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Don't have an account? Click here to sign up...");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_username_30px_1.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 30, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_sign_in_form_password_30px.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 30, 30));

        usersigninbtn.setBackground(new java.awt.Color(0, 153, 0));
        usersigninbtn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        usersigninbtn.setForeground(new java.awt.Color(204, 255, 204));
        usersigninbtn.setText("Sign In");
        usersigninbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 2, true));
        usersigninbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersigninbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersigninbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersigninbtnMouseExited(evt);
            }
        });
        usersigninbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersigninbtnActionPerformed(evt);
            }
        });
        jPanel3.add(usersigninbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 100, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordloginActionPerformed

    private void passwordloginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordloginFocusGained
        // TODO add your handling code here:
        passwordlogin.setText("");
    }//GEN-LAST:event_passwordloginFocusGained

    private void usernameloginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameloginFocusGained
        // TODO add your handling code here:
        usernamelogin.setText("");
    }//GEN-LAST:event_usernameloginFocusGained

    private void stuloginclosebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuloginclosebtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new images().setVisible(true);
    }//GEN-LAST:event_stuloginclosebtnMouseClicked

    private void usernameloginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameloginFocusLost
        // TODO add your handling code here:
        if (usernamelogin.getText().trim().equals("") || usernamelogin.getText().trim().toLowerCase().equals("Username")) {
            usernamelogin.setText("Username");
            usernamelogin.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_usernameloginFocusLost

    private void passwordloginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordloginFocusLost
        // TODO add your handling code here:

        //get the password text
        String pass = String.valueOf(passwordlogin.getPassword());
        if (pass.trim().toLowerCase().equals("Password")) {
            passwordlogin.setText("Password");
            passwordlogin.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_passwordloginFocusLost

    private void usersigninbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersigninbtnMouseClicked
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;

        //get username and password 
        String Username = usernamelogin.getText();
        String Password = String.valueOf(passwordlogin.getPassword());

        //sql to check the query details
        String query = "select * from users where username=? and password=?";

        //show a message if username or password fields are empty
        if (Username.trim().equals("Username")) {
            JOptionPane.showMessageDialog(this, "Enter Username", "Empty Username", 2);
        } else if (Password.trim().equals("Password")) {
            JOptionPane.showMessageDialog(this, "Enter Password", "Empty Password", 2);
        } else {
            try {
                ps = connectionProvider.getCon().prepareStatement(query);
                ps.setString(1, Username);
                ps.setString(2, Password);
                rs = ps.executeQuery();
                if (rs.next()) {
                    //show menu form
                    menu form = new menu();
                    form.setVisible(true);
                    form.pack();
                    form.setLocationRelativeTo(null);
                    //close login form
                    this.dispose(); 
                } else {
                    //error message
                    JOptionPane.showMessageDialog(this, "Invalid Username And Password", "Login Error", 2);
                }
            } catch (SQLException ex) {
                Logger.getLogger(userSignin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_usersigninbtnMouseClicked

    private void usersigninbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersigninbtnMouseEntered
        // TODO add your handling code here:
        usersigninbtn.setBackground(new Color(120, 100, 40));
    }//GEN-LAST:event_usersigninbtnMouseEntered

    private void usersigninbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersigninbtnMouseExited
        // TODO add your handling code here:
        usersigninbtn.setBackground(new Color(0, 153, 0));
    }//GEN-LAST:event_usersigninbtnMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new usersign().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void usersigninbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersigninbtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_usersigninbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userSignin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField passwordlogin;
    private javax.swing.JButton stuloginclosebtn;
    private javax.swing.JTextField usernamelogin;
    private javax.swing.JButton usersigninbtn;
    // End of variables declaration//GEN-END:variables
}

//references
//https://youtu.be/3vauM7axnRs
//https://youtu.be/PhySllnCBvo
//https://youtu.be/QYDycJhyIv4